CodeCraft-Solutions-DREAM-Lab/Front-End

DREAM Lab Frontend/package-lock.json
DREAM Lab Frontend/package.json
DREAM Lab Frontend/src/output.css

- Modificar package.json para que al correr dev o start, se corra tanto la app como el config de tailwind para que cuando se editen archivos, se actualice automáticamente el archivo de tailwind.
- #62

Correr config de tailwind al mismo tiempo que app

---

DREAM Lab Frontend/package-lock.json
DREAM Lab Frontend/package.json
DREAM Lab Frontend/src/Global/Auth.js
DREAM Lab Frontend/src/Global/Database.js
DREAM Lab Frontend/src/Global/ProtectedRoutes.jsx
DREAM Lab Frontend/src/output.css

- Agregar funciones de ayuda para hacer llamadas a la API

Cambiar las ayudas para hacer llamadas a la bd usando axios

---

DREAM Lab Frontend/src/Global/ProtectedRoutes.jsx
DREAM Lab Frontend/src/LandingPage/LandingPage.jsx
DREAM Lab Frontend/src/output.css

- Corregir autenticación de token en rutas protegidas. En el último PR cambié a realizar las llamadas usando Axios, pero se me pasó encapsular en un try catch lo que se recibe de la llamada. Por lo que al recibir el error de que el token era inválido, se quedaba la página en la pantalla de carga.
- Agregar en la ruta raíz "/" o landing page un botón para saltarse el login. Marca en redux como que has iniciado sesión y se guarda un token que no tiene vencimiento en tu local storage.

Skip login

---

DREAM Lab Frontend/src/Home/RecommendationsCarousel.css
DREAM Lab Frontend/src/Home/RecommendationsCarousel.jsx

- Dots de navegación
- El carrusel gira automáticamente por defecto
- Si se interactua con él, deja de girar
- U10_T4 - Implementar movimiento en bucle del carrusel por tiempo o por flechas.

Movimiento automático de carrusel

---

DREAM Lab Frontend/src/App.css

- Pequeño update de App.css para la responsividad de la SpeechBotCard
N/A

Mini update App.css

---

DREAM Lab Frontend/src/components/general/Logout.jsx

- Ahora cuando de cierra sesión se borran los datos del usuario del local storage
N/A

Update a cerrar sesión

---

DREAM Lab Frontend/src/App.jsx
DREAM Lab Frontend/src/Global/Storage.js
DREAM Lab Frontend/src/Login/LoginPage/LoginPage.jsx
DREAM Lab Frontend/src/Profile/Profile.jsx
DREAM Lab Frontend/src/components/general/Logout.jsx

- Agregar función para borrar tanto el local como el session storage

Agregar funcion para limpiar session y local storage

---

DREAM Lab Frontend/src/Global/Auth.js
DREAM Lab Frontend/src/Global/ProtectedRoutes.jsx
DREAM Lab Frontend/src/Login/LoginPage/LoginPage.jsx
DREAM Lab Frontend/src/Login/LoginTextField/LoginTextField.jsx

- Agregar validaciones al login por si los campos están vacíos
- Agregar mensajes de error para señalarle al usuario la razón por la que falló la operación
- #22

Login error handling

---

DREAM Lab Frontend/src/Login/LoginPage/LoginPage.jsx

- Cuando se tenga guardado en localstorage un token, validar si es válido y de serlo, saltarse el login

Auto skip login

---

DREAM Lab Frontend/src/Global/ProtectedRoutes.jsx
DREAM Lab Frontend/src/Global/ProtectedRoutes2.jsx
DREAM Lab Frontend/src/Login/LoginPage/LoginPage.jsx

- Simplificar la lógica de las rutas protegidas
- Remover punto y coma accidental en la página de login

Simplificar la logica de las rutas protegidas

---

DREAM Lab Frontend/src/Home/Detalles.jsx

- Cambié la navegación a la nueva pantalla de reservación cuando se le pica al botón solicitar
- N/A

Mini update Detalles.jsx - Navegacion a la nueva pantalla de reservacion

---

DREAM Lab Frontend/src/Reservaciones/SelectorSala.jsx

- Pequeña correción en el estilo del botón aceptar
N/A

Update front boton aceptar

---

DREAM Lab Frontend/src/Home/RecomendacionesInvalidas.css
DREAM Lab Frontend/src/Home/RecommendationsCarousel.css
DREAM Lab Frontend/src/Home/RecommendationsCarousel.jsx

- Mejora aviso de recomendaciones inválidas
- Fix bug de distorsión de imágenes
- Fix estetico y de bug de distorsión de imágenes
- Fix

Fix Tarjetas de Recomendaciones

---

DREAM Lab Frontend/src/Home/HomePage.jsx
DREAM Lab Frontend/src/Home/RecommendationsCarousel.jsx

Add nav a reservación

---

DREAM Lab Frontend/src/Home/SpeechBotCard.jsx
DREAM Lab Frontend/src/Home/TextField.jsx

- Se deshabilita el micrófono cuando el navegador no maneja la librería de react-speech-recognition
- Se agregó un placeholder en el input

Detalles finales en input

---

DREAM Lab Frontend/src/Profile/Profile.jsx

- Modificar fechas precargadas de los modales al cancelar una reservación para que concuerden

Cambiar fechas de modal de cancelar reservacion para que concuerden

---

DREAM Lab Frontend/src/pages/HomePage/HomePage.jsx
DREAM Lab Frontend/src/pages/HomePage/components/ImageSlider/ImageSlider.jsx

- Cambiar peticiones del image slider para que no estén dentro del HomePage, y estén mejor dentro del componente

Peticiones imageslider

---

DREAM Lab Frontend/firebase-config.js
DREAM Lab Frontend/package-lock.json
DREAM Lab Frontend/package.json
DREAM Lab Frontend/src/App.jsx
DREAM Lab Frontend/src/GlobalComponents/GlassCard/GlassCard.css
DREAM Lab Frontend/src/GlobalComponents/GlassCard/GlassCard.jsx
DREAM Lab Frontend/src/main.jsx
DREAM Lab Frontend/src/pages/Videowall/Videowall.css
DREAM Lab Frontend/src/pages/Videowall/Videowall.jsx
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/Anuncios.css
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/Anuncios.jsx
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/components/Hora/Hora.css
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/components/Hora/Hora.jsx
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/components/InfoEvento/InfoEvento.css
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/components/InfoEvento/InfoEvento.jsx
DREAM Lab Frontend/src/pages/Videowall/components/CarouselReservaciones/CarouselReservaciones.css
DREAM Lab Frontend/src/pages/Videowall/components/CarouselReservaciones/CarouselReservaciones.jsx

- Muestra de anuncios con movimiento por tiempo
- Los anuncios son hardcodeados
- Componentes de hora e info de anuncios
- Config de Firebase

Update de U50 visualizar material audiovisual en el video wall

---

DREAM Lab Frontend/src/pages/Videowall/Videowall.css
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/components/Hora/Hora.css
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/components/InfoEvento/InfoEvento.css

- Ordenamiento de los estilos de css del anuncio

Fix Ordenamiento de Estilos de Css

---

DREAM Lab Frontend/src/pages/HomePage/HomePage.jsx
DREAM Lab Frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.css

- Al formatear el css en 2 líneas se había perdido una parte del código. Corregido

Fix css de recomendaciones

---

DREAM Lab Frontend/src/pages/HomePage/HomePage.jsx
DREAM Lab Frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.css

Reverts CodeCraft-Solutions-DREAM-Lab/Front-End#117

Revert "Fix css de recomendaciones"

---

DREAM Lab Frontend/src/pages/HomePage/HomePage.jsx
DREAM Lab Frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.css

Reverts CodeCraft-Solutions-DREAM-Lab/Front-End#120

Revert "Revert "Fix css de recomendaciones""

---

DREAM Lab Frontend/package-lock.json
DREAM Lab Frontend/package.json
DREAM Lab Frontend/src/pages/LoginPage/LoginPage.jsx
DREAM Lab Frontend/src/pages/LoginPage/components/LoginButton/LoginButton.jsx
DREAM Lab Frontend/src/pages/Videowall/Videowall.css
DREAM Lab Frontend/src/pages/Videowall/Videowall.jsx
DREAM Lab Frontend/src/pages/Videowall/components/Anuncios/Anuncios.jsx
DREAM Lab Frontend/src/pages/Videowall/components/ReservacionesVideowall/ReservacionesVideowall.css
DREAM Lab Frontend/src/pages/Videowall/components/ReservacionesVideowall/ReservacionesVideowall.jsx
DREAM Lab Frontend/src/pages/Videowall/components/ReservacionesVideowall/components/CarouselReservaciones/CarouselReservaciones.css
DREAM Lab Frontend/src/pages/Videowall/components/ReservacionesVideowall/components/CarouselReservaciones/CarouselReservaciones.jsx
DREAM Lab Frontend/src/pages/Videowall/components/ReservacionesVideowall/components/CarouselReservaciones/components/ReservationCard.css
DREAM Lab Frontend/src/pages/Videowall/components/ReservacionesVideowall/components/CarouselReservaciones/components/ReservationCard.jsx
DREAM Lab Frontend/tailwind.config.js

Reverts CodeCraft-Solutions-DREAM-Lab/Front-End#121

Revert "Revert "Carousel test""

---

DREAM Lab Frontend/src/pages/SeleccionMaterial/SeleccionMaterial.css
DREAM Lab Frontend/src/pages/SeleccionMaterial/SeleccionMaterial.jsx
DREAM Lab Frontend/src/pages/SeleccionMaterial/components/MaterialCard.jsx
DREAM Lab Frontend/src/pages/SelectorSala/SelectorSala.jsx

- Cambio de nombres de clases en css
- N/A

Fix nombres de clases css selector sala y seleccion material

---

DREAM Lab Frontend/src/pages/HomePage/HomePage.jsx

- Inicialización de variables en falso al procesar texto
- Bug de recomendacioes

Fix bug recomendaciones validas después de inválidas

---

DREAM Lab Frontend/.eslintrc.cjs
DREAM Lab Frontend/cypress/e2e/login.cy.js
DREAM Lab Frontend/package-lock.json
DREAM Lab Frontend/package.json
DREAM Lab Frontend/src/pages/LoginPage/LoginPage.jsx
DREAM Lab Frontend/src/pages/LoginPage/components/LoginButton/LoginButton.jsx
DREAM Lab Frontend/src/pages/LoginPage/components/LoginTextField/LoginTextField.jsx

- Agregar pruebas para la pagina del login.
- Agregar función de ESLint para eliminar detección errónea de funciones de Cypress
- Eliminar GSAP (creo que lo había agregado yo y nunca lo terminé utilizando).
- Agregar identificadores a componentes para ser referenciados en las pruebas de Cypress.

Pruebas cypress login

---

dream-lab-frontend/cypress/e2e/login.cy.js
dream-lab-frontend/cypress/support/commands.js

- Agregar comandos para escribir texto y presionar componentes con el atributo data-cy.
- Agregar comando hijo para checar si un componente tiene un cierto atributo.
- Modificar las pruebas de login para que utilicen los comandos

Agregar comandos y modificar pruebas de login para usarlos

---

dream-lab-frontend/cypress/e2e/login.cy.js
dream-lab-frontend/cypress/support/commands.js
dream-lab-frontend/src/GlobalComponents/NavBar/NavBar.jsx

- Agregar break a navbar para que funcione el navbar para el landingpage
- Agregar data-cy para el navbar para referenciarlo en las pruebas de cypress
- Crear comando para contains en cypress

Agregar data-cy a navbar y comando contains

---

dream-lab-frontend/cypress/e2e/selectorSala.cy.js
dream-lab-frontend/cypress/support/commands.js
dream-lab-frontend/src/pages/SelectorSala/components/TextoNombreSala/TextoNombreSala.jsx

Merge con algunas de las pruebas de select-sala, no son todos
-

Test select sala 2

---

dream-lab-frontend/src/pages/SeleccionMaterial/SeleccionMaterial.jsx
dream-lab-frontend/src/pages/SeleccionMaterial/components/SearchBar/SearchBar.jsx

- Cuando se escribe se filtran las tarjetas en tiempo real
- U27

Add filtrado de materiales en tiempo real por texto

---

dream-lab-frontend/src/pages/SeleccionMaterial/components/SearchBar/SearchBar.jsx

- Blur cuando se escribe enter
- U27_T4

Blur de barra con Enter

---

dream-lab-frontend/cypress/cypress.config.js
dream-lab-frontend/cypress/cypress/cypress.config.js
dream-lab-frontend/cypress/cypress/cypress/fixtures/example.json
dream-lab-frontend/cypress/cypress/cypress/support/commands.js
dream-lab-frontend/cypress/cypress/cypress/support/e2e.js
dream-lab-frontend/cypress/cypress/fixtures/example.json
dream-lab-frontend/cypress/cypress/support/commands.js
dream-lab-frontend/cypress/cypress/support/e2e.js
dream-lab-frontend/cypress/e2e/cancelarReservacion.cy.js
dream-lab-frontend/cypress/e2e/detalles.cy.js
dream-lab-frontend/cypress/e2e/slider.cy.js
dream-lab-frontend/cypress/support/commands.js
dream-lab-frontend/src/GlobalComponents/NavBar/NavBar.jsx
dream-lab-frontend/src/GlobalComponents/NuevoIconoLogro/NuevoIconoLogro.css
dream-lab-frontend/src/pages/HomePage/components/Detalles/Detalles.jsx
dream-lab-frontend/src/pages/HomePage/components/Detalles/components/BotonSolicitar/BotonSolicitar.jsx
dream-lab-frontend/src/pages/HomePage/components/Detalles/components/Etiqueta/Etiqueta.jsx
dream-lab-frontend/src/pages/HomePage/components/ImageSlider/ImageSlider.jsx
dream-lab-frontend/src/pages/Profile/components/EsferaPuntosPrioridad/EsferaPuntosPrioridad.jsx
dream-lab-frontend/src/pages/Profile/components/NameCard/NameCard.jsx
dream-lab-frontend/src/pages/SelectorSala/components/Slider/Slider.jsx

-- Cambios menores en el menú de experiencias. Se agregaron pruebas de Cypress.

Pull dev intento3

---

.github/workflows/cypress-tests.yml
dream-lab-frontend/cypress.config.js
dream-lab-frontend/cypress/e2e/selectorSala.cy.js
dream-lab-frontend/cypress/support/commands.js

- Configurar GH Action para cypress

Cypress gh action

---

dream-lab-frontend/cypress/e2e/cancelarReservacion.cy.js
dream-lab-frontend/package-lock.json

- Refactor de pruebas del perfil

refactor pruebas

---

.github/workflows/cypress-tests.yml
dream-lab-frontend/cypress/e2e/login.cy.js
dream-lab-frontend/cypress/support/commands.js
dream-lab-frontend/package-lock.json

- Agregar waits que intercepten las llamadas a la api al login para evitar errores de timeout.

Correccion pruebas login

---

dream-lab-frontend/src/GlobalComponents/NavBar/NavBar.css
dream-lab-frontend/src/GlobalComponents/NavBar/components/SearchBar/SearchBar.css
dream-lab-frontend/src/GlobalComponents/NavBar/components/SearchBar/SearchBar.jsx
dream-lab-frontend/src/pages/Profile/Profile.css

- Cambios en css de la searchbar (navbar)

css searchbar

---

.github/pull_request_template.md

Actualizar PR template

---

dream-lab-frontend/cypress/e2e/recomendacionesVoz.cy.js
dream-lab-frontend/src/pages/HomePage/components/RecomendacionesInvalidas/RecomendacionesInvalidas.jsx
dream-lab-frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.jsx
dream-lab-frontend/src/pages/HomePage/components/SpeechBotCard/components/SendButton/SendButton.jsx
dream-lab-frontend/src/pages/HomePage/components/SpeechBotCard/components/TextField/TextField.jsx

- Pruebas de cypress de recomendaciones por voz

Pruebas recomendaciones por voz

---

dream-lab-frontend/cypress/e2e/login.cy.js
dream-lab-frontend/cypress/support/commands.js

- Agregar más tiempo de espera para cargar el homepage

Modificar el timeout para el login valido

---

dream-lab-frontend/src/pages/Videowall/Videowall.jsx
dream-lab-frontend/src/pages/Videowall/components/HiddenInputLogger/HiddenInputLogger.jsx
dream-lab-frontend/src/pages/Videowall/components/ReservacionesVideowall/components/CarouselReservaciones/CarouselReservaciones.jsx

- Agregar autorefresh al videowall
- Agregar eventlistener para obtener qr de login

Auto update videowall

---

dream-lab-frontend/src/GlobalComponents/NavBar/components/SearchBar/SearchBar.css
dream-lab-frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.css
dream-lab-frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.jsx

- Responsividad recomendaciones
- Small fix responsividad SearchBar
- Reserva por click en recomendaciones

Recomendaciones separadas

---

dream-lab-frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.css
dream-lab-frontend/src/pages/HomePage/components/RecommendationsCarousel/RecommendationsCarousel.jsx

- Ya no se hace scroll horizontal fuera de la página en móvil

Small fix responsividad en móvil

---

dream-lab-frontend/src/pages/Videowall/components/HiddenInputLogger/HiddenInputLogger.jsx

- Actualizar datos del endpoint para iniciar sesión con tagID

Actualizar endpoint para iniciar sesion con tagId

---

dream-lab-frontend/cypress/e2e/cronogramaAdmin.cy.js
dream-lab-frontend/cypress/e2e/resumenReserva.cy.js
dream-lab-frontend/cypress/e2e/selectorMaterial.cy.js
dream-lab-frontend/src/pages/CronogramaAdmin/CronogramaAdmin.jsx
dream-lab-frontend/src/pages/ResumenReservacion/components/InfoReservCardDupe/InfoReservCardDupe.jsx
dream-lab-frontend/src/pages/SeleccionMaterial/SeleccionMaterial.jsx

- Pruebas cypress: cronograma, resumen reservación, resumen materiales

Pruebas cypress

---

dream-lab-frontend/cypress/e2e/cronogramaAdmin.cy.js
dream-lab-frontend/timings.json

- Actualizar timings de las pruebas
- Agregar import para que funcionen las pruebas del cronograma

Pruebas cypress paralelas

---

dream-lab-frontend/src/pages/ResumenReservacion/ResumenReservacion.jsx

- Cmabie el estatus con el que se mandan reservaciones

fix estatus reservaciones

---

dream-lab-frontend/src/pages/LandingPage/LandingPage.css

- Se cambió extensión de .png a .webp para una de las imágenes

Corregir extensión de imágen

---

README.md
dream-lab-frontend/package.json

- Actualizar scripts para quitar --open del script de start.
- Actualizar documentación del readme.

Actualizar reacme e scripts

---

.github/workflows/azure-static-web-apps-lively-grass-0af65cc0f.yml
README.md

- Remover el cierre del PR que era innecesario.
- Actualizar instrucciones de readme para correr los comandos en la carpeta del proyecto.

Actualizar readme y workflow de despliegue

---

dream-lab-frontend/src/App.jsx
dream-lab-frontend/src/pages/ErrorPage/ErrorPage.jsx
dream-lab-frontend/src/pages/NotFound/NotFound.jsx

- Agregar página de error.
- Configurar las rutas para desplegar página de error en caso de que suceda uno.

Agregar pantalla de error y configurar errorElement

---

dream-lab-frontend/cypress/e2e/agregarAnucio.cy.js
dream-lab-frontend/cypress/e2e/cancelarReservacion.cy.js
dream-lab-frontend/cypress/e2e/cronogramaAdmin.cy.js
dream-lab-frontend/cypress/e2e/dashboard.cy.js
dream-lab-frontend/cypress/e2e/detalles.cy.js
dream-lab-frontend/cypress/e2e/login.cy.js
dream-lab-frontend/cypress/e2e/personalizacionLogros.cy.js
dream-lab-frontend/cypress/e2e/recomendacionesVoz.cy.js
dream-lab-frontend/cypress/e2e/resumenReserva.cy.js
dream-lab-frontend/cypress/e2e/selectorMaterial.cy.js
dream-lab-frontend/cypress/e2e/selectorSala.cy.js
dream-lab-frontend/cypress/e2e/slider.cy.js
dream-lab-frontend/cypress/support/commands.js
dream-lab-frontend/timings.json

- Corregir las pruebas de cypress que fallaron tras hacer cambios al login

Filtros cronograma

---

dream-lab-frontend/src/pages/CronogramaAdmin/CronogramaAdmin.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/Cronograma/CustomItemRenderer.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/ReservItemModal.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/SolicitedMatsListModal.jsx

- Ya se cambian los colores en la reservación dependiendo de su estatus de materiales

Resto de modal admin pt1

---

dream-lab-frontend/src/GlobalComponents/NavBar/NavBar.jsx
dream-lab-frontend/src/GlobalComponents/NavBarAdmin/NavBarAdmin.jsx
dream-lab-frontend/src/pages/CrearAnuncioVideowall/CrearAnuncioVideowall.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/CronogramaAdmin.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalCrearReservacionAdmin/ModalCrearReservacionAdmin.css
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalCrearReservacionAdmin/ModalCrearReservacionAdmin.jsx
dream-lab-frontend/src/pages/Dashboard/Dashboard.jsx
dream-lab-frontend/src/pages/HomePage/components/Detalles/Detalles.jsx
dream-lab-frontend/src/pages/ResumenReservacion/ResumenReservacion.jsx
dream-lab-frontend/src/pages/SeleccionMaterial/SeleccionMaterial.jsx
dream-lab-frontend/src/pages/SelectorSala/SelectorSala.jsx

- Crear modal para especificar nombre y sala para las reservaciones de admin
- Enrutar crear reservación en el cronograma con el flujo de reservación
- Modificar navbar cuando el administrador está haciendo una reservación desde el botón del cronograma.
- Agregar nombre alterno a las reservaciones del administrador para que ese nombre sea el que se despliega.

Reservaciones admin

---

dream-lab-frontend/src/pages/CronogramaAdmin/CronogramaAdmin.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/CancelarReservaModalButton.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/ModalCancelarReserv/ModalCancelarReserv.css
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/ModalCancelarReserv/ModalCancelarReserv.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/ModalPenalizar/ModalPenalizar.css
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/ModalPenalizar/ModalPenalizar.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/PenalizarModalButton.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/ReservItemModal.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/SolicitedMatsListModal.jsx

- Ya quedaron todos los modales
- Ánimo, esto ni siquiera lo va a ver el socio

Resto de modal admin

---

dream-lab-frontend/src/pages/Videowall/components/AlertaAsistencia/AlertaAsistencia.css
dream-lab-frontend/src/pages/Videowall/components/AlertaAsistencia/AlertaAsistencia.jsx

Responsividad

---

dream-lab-frontend/cypress/e2e/vistaEstudiante.cy.js
dream-lab-frontend/src/App.jsx
dream-lab-frontend/src/GlobalComponents/NavBar/components/Logout/Logout.jsx
dream-lab-frontend/src/GlobalComponents/NavBarAdmin/NavBarAdmin.jsx
dream-lab-frontend/src/GlobalComponents/ProtectedRoutes/ProtectedRoutes.jsx
dream-lab-frontend/src/redux/Slices/userSlice.js

- Agreegar logout para vista de administrador

Agregar logout para admin

---

dream-lab-frontend/cypress/e2e/vistaEstudiante.cy.js

- Desglosar pruebas de la vista de estudiante.

Desglosar pruebas

---

dream-lab-frontend/cypress/e2e/agregarReservacionAdmin.cy.js
dream-lab-frontend/cypress/support/commands.js
dream-lab-frontend/src/pages/CronogramaAdmin/CronogramaAdmin.jsx

- Agregar botón para presionar botones escondidos y del speed dial

Agregar comando para presionar botones de speed dial

---

dream-lab-frontend/cypress/e2e/agregarReservacionAdmin.cy.js
dream-lab-frontend/cypress/support/commands.js
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalCrearReservacionAdmin/ModalCrearReservacionAdmin.jsx

- Agregar pruebas para las reservaciones de administrador.
-  Agregar función para borrar campos del modal de reservación de admin cuando se cierra.
- Agregar comandos de cypress para validar la visibilidad y si existe un componente.

Cypress reservacion admin

---

dream-lab-frontend/cypress/e2e/cronogramaAdmin_ModalInfo.cy.js
dream-lab-frontend/cypress/fixtures/cronogramaAdmin_ModalInfo/estatus.json
dream-lab-frontend/cypress/fixtures/cronogramaAdmin_ModalInfo/mesas.json
dream-lab-frontend/cypress/fixtures/cronogramaAdmin_ModalInfo/reservaciones_cronograma.json
dream-lab-frontend/cypress/fixtures/cronogramaAdmin_ModalInfo/salas.json
dream-lab-frontend/cypress/fixtures/cronogramaAdmin_ModalInfo/salas_cronograma.json
dream-lab-frontend/src/pages/CronogramaAdmin/CronogramaAdmin.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/ModalReservInfo/ReservItemModal.jsx

- Quité una llamada innecesaria en el cronograma
- Agregué todas las fixtures (para ejemplo) para la prueba de cypess
- El modal de info ya muestra el nombre de la mesa

Fixtures de cypress

---

dream-lab-frontend/src/pages/MaterialesRecomendados/MaterialesRecomendados.jsx

- Fix de bug, no se mandaba el idSala correcto

fix de bug de materiales recomendados en creación de experiencia

---

dream-lab-frontend/src/pages/ResumenReservacion/ResumenReservacion.jsx

- Ahora si se mandan los materiales de la reserva y se guardan

Ahora si se mandan los materiales de la reserva

---

dream-lab-frontend/cypress/e2e/logros.cy.js
dream-lab-frontend/cypress/e2e/resumenReserva.cy.js

- Fix pruebas cypress resumen de reserva

Fix pruebas cypress resumen de reserva

---

dream-lab-frontend/cypress/e2e/cambiarDisponibilidad.cy.js
dream-lab-frontend/src/pages/CronogramaAdmin/components/GestionSalas/GestionSalas.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/GestionSalas/components/ConfirmacionGuardado.jsx
dream-lab-frontend/src/pages/CronogramaAdmin/components/GestionSalas/components/GuardarConfiguracion.jsx

- Add pruebas de disponibilidad de salas

A38 disponibilidad de salas pruebas cypress

---

dream-lab-frontend/src/pages/HomePage/HomePage.jsx

- Cambiar endpoint de "/ultimas" a "/recomendaciones"

Cambiar endpoint de recomendaciones

---

dream-lab-frontend/src/pages/CronogramaAdmin/components/GestionSalas/components/GuardarConfiguracion.jsx

- Update Texto Disponibilidad Salas

Update texto de cancelaciones por disponibilidad

---

dream-lab-frontend/src/App.css
dream-lab-frontend/src/pages/SelectorSala/components/InfoReservCard/InfoReservCard.css

- A ver si ahora sí jaló el error del overflow

Actualizar acomodo solicitud fecha

---

dream-lab-frontend/src/pages/SelectorSala/SelectorSala.css
dream-lab-frontend/src/pages/SelectorSala/components/InfoReservCard/InfoReservCard.css
dream-lab-frontend/src/pages/SelectorSala/components/Slider/Slider.css

- Fix bugs visuales de selector sala y responsividad

fix selector sala y responsividad
